services:
  backend:
    build: ./backend
    container_name: django-backend
    ports:
      - "4020:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - ALLOWED_HOSTS=*
    restart: unless-stopped
    networks:
      - prms_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile          # your dev Dockerfile
    container_name: react-frontend
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "4021:4021"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - prms_network

networks:
  prms_network:
    driver: bridge
